---
# tasks file for gitlab-runner
- name: install runner
  apt:
    deb: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb

- name: gitlab-runner start
  systemd:
    name: gitlab-runner
    state: started

# - name: "Register runner"
#   community.general.gitlab_runner:
#     api_url: "{{ gitlab_api_url }}"
#     # api_token: "{{ access_token }}"
#     registration_token: "{{ registration_token }}"
#     description: Docker Machine t1
#     state: present
#     active: True
#     tag_list: ['docker']
#     run_untagged: False
#     locked: False
