---
- name: packer app provision
  hosts: all
  become: true
  tasks:
    - name: sleep 30s
      pause:
        seconds: "30"
    - name: apt update and install ruby
      apt:
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
          - git
        update_cache: yes
