---
- name: Configure mongodb
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  handlers:
    - name: restart mongod
      systemd:
        name: mongod
        state: restarted
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify:
        - restart mongod

- name: deploy application
  hosts: app
  tags: deploy-tag
  become: true
  vars:
    username: ubuntu
  handlers:
    - name: reload puma
      become: true
      systemd:
        name: puma
        state: restarted
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/{{ username }}/reddit'
        version: monolith
      # notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: '/home/{{ username }}/reddit'
      # notify: reload puma


- name: Configure host
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.130.0.14
    username: ubuntu
  handlers:
    - name: reload puma
      become: true
      systemd:
        name: puma
        state: restarted
  tasks:
    - name: Add unit file for Puma
      template:
        src: templates/puma.service.j2
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: '/home/{{ username }}/db_config'
        owner: '{{ username }}'
        group: '{{ username }}'
      notify: reload puma

    - name: enable puma
      systemd:
        name: puma
        enabled: true
        state: started
        daemon_reload: true
