---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.130.0.15
    username: ubuntu
  handlers:
    - name: restart mongod
      become: true
      systemd:
        name: mongod
        state: restarted
    - name: reload puma
      become: true
      systemd:
        name: puma
        state: restarted
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify:
        - restart mongod

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/{{ username }}/reddit'
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: '/home/{{ username }}/reddit'
      tags: deploy-tag

    - name: Add unit file for Puma
      become: true
      template:
        src: templates/puma.service.j2
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      become: true
      template:
        src: templates/db_config.j2
        dest: '/home/{{ username }}/db_config'
      tags: app-tag
      notify: reload puma

    - name: enable puma
      become: true
      systemd:
        name: puma
        enabled: true
        state: started
        daemon_reload: true
      tags: app-tag
