name: linter-push
on:
  push:
    # branches:
    #   - '!main'


jobs:
  otus-homeworks:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: express42/otus-homeworks
          path: otus-homeworks
          ref: 2020-11
      - name: Get versions
        run: 'echo -=Get versions=-; ansible --version; ansible-lint --version; packer version; terraform version; tflint --version; docker version; docker-compose --version'
      - name: run test otus
        run: cd  $GITHUB_WORKSPACE && ./otus-homeworks/homeworks/${GITHUB_REF##*/}/run.sh

  lint-packer:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get versions
        run: 'echo -=Get versions=-; ansible --version; ansible-lint --version; packer version; terraform version; tflint --version; docker version; docker-compose --version'
      - name: packer validate app
        run: packer validate -var-file=packer/variables.json.example packer/app.json
      - name: packer validate db
        run: packer validate -var-file=packer/variables.json.example packer/db.json
  lint-terraform:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get versions
        run: 'echo -=Get versions=-; ansible --version; ansible-lint --version; packer version; terraform version; tflint --version; docker version; docker-compose --version'
      - name: terraform validate stage
        run: cd terraform/stage && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example
      - name: tflint stage
        run: tflint terraform/stage
      - name: terraform validate prod
        run: cd terraform/prod && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example
      - name: tflint prod
        run: tflint terraform/prod
  lint-ansible:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get versions
        run: 'echo -=Get versions=-; ansible --version; ansible-lint --version; packer version; terraform version; tflint --version; docker version; docker-compose --version'
      - name: ansible lint
        # run: cd ansible && ansible-lint
        run: cd ansible && echo "NO SECRETS =("
        env:
          ANSIBLE_VAULT_PASSWORD: get_secret_please
