name: linter
on:
  push:
    branches:
      - master
      - ansible-3
  pull_request:
    branches:
      - master

jobs:
  otus-homeworks:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        path: '/srv'
      - name: run otus test
        run: pwd && ls -lah && env | grep REF && echo ${GITHUB_REF##*/} && cd $GITHUB_WORKSPACE
      - name: run test otus
        run: cd  $GITHUB_WORKSPACE && ./otus-homeworks/homeworks/${GITHUB_REF##*/}/run.sh


  lint-packer:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: packer validate app
        run: packer validate -var-file=packer/variables.json.example packer/app.json
      - name: packer validate db
        run: packer validate -var-file=packer/variables.json.example packer/db.json
  lint-terraform:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: terraform validate stage
        run: cd terraform/stage && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example
      - name: tflint stage
        run: tflint terraform/stage
      - name: terraform validate prod
        run: cd terraform/prod && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example
      - name: tflint prod
        run: tflint terraform/prod
  lint-ansible:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    # needs: ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: ansible lint
        # run: cd ansible && ansible-lint
        run: cd ansible && echo "NO SECRETS =("
        env:
          ANSIBLE_VAULT_PASSWORD: get_secret_please
        # - name: Build
      #   run: docker build -t ansible-lint .
      # - name: Tags
      #   run: |
      #     docker tag ansible-lint ${{ github.repository }}:${{ github.sha }}
      #     docker tag ansible-lint ${{ github.repository }}:latest
      # - name: check install
      #   run: |
      #     docker images
      #     docker run --rm ${{ github.repository }}:${{ github.sha }} ansible --version
      #     docker run --rm ${{ github.repository }}:${{ github.sha }} ansible-lint --version
      #     docker run --rm ${{ github.repository }}:${{ github.sha }} ssh -V
      #     docker run --rm ${{ github.repository }}:${{ github.sha }} bash --version
      # - name: Push to Docker Hub
      #   run: |
      #     docker push ${{ github.repository }}:${{ github.sha }}
      #     docker push ${{ github.repository }}:latest
      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      #     registry: ghcr.io
      #     repository: ${{ github.repository }}
      #     tag_with_ref: true
